---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyproxy-config
  namespace: kube-system
data:
  tinyproxy.conf: |
    Port 3128
    Listen 0.0.0.0
    Timeout 600
    Allow 127.0.0.1
    Allow 10.42.0.0/16
    Allow 10.43.0.0/16
    DisableViaHeader Yes
    LogLevel Critical
    MaxClients 100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tinyproxy
  namespace: kube-system
  labels:
    app: tinyproxy
spec:
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      hostNetwork: true
      containers:
      - name: tinyproxy
        image: vimagick/tinyproxy:latest
        ports:
        - containerPort: 3128
          hostPort: 3128
        volumeMounts:
        - name: config
          mountPath: /etc/tinyproxy/tinyproxy.conf
          subPath: tinyproxy.conf
      volumes:
      - name: config
        configMap:
          name: tinyproxy-config
