apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:Q8FrkfBPv+KY8KJj+wnM2KD2yg6X3UYPjhZcJ593hmmJGSOaRWw3f0/OdVIUF+Mf7mkuSt5Glviw5cxJjVeZ27veP3LPM7HHg65Llt8kKgwJgUOJXsFsZegPkiGUj3kMTm+0Z2R/b9Fo/vWi44ApOJ4flxDILk57waWURA4kRk/+FRp04dRccjlOrgQxUGfKcXrAKilkkp/tbRXFbS0nQI8DHASx32WFPuUgGIzQ++zs/Z1hwhkBRA==,iv:Qa8/VEt/lVH9FoHv566kAlb4muNmFA1f8UgTbT1XC1c=,tag:bisCLB9FAwc+9a8eOUNrzQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: admin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x23xy95kpc6h3ql9x4q35r8r2g5yd0mjejggz55a2mnc5muwys2qreflxt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArajF3dzZpOUgvMzd1QnBj
            blJqa00yOFc0VHFudjZ0N0I1V2dvUmd6eWxvCnduSFA5eno2amJHNjUrMjhOUzhD
            Q1JzeHdyOUI4aE9ETTZnYVQyUVgvcTAKLS0tIDYvZFJUWG1vL0VUcHhYQlA2TmZ4
            d0Z0S3ptTS9wcEpERVh3U3FFUllmUWMK/WiSzgvxVsEhJe17+vKjhSZvswKNx7sc
            KCbQFskJQvw9XaP+FuJNpKElRKer2V5s9UvajiAp7rG/HG8uyKWduQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T13:18:29Z"
    mac: ENC[AES256_GCM,data:ER/3VR+VStPgX5QADhO1GGmABoUH27fkMirBgT/NAFVHPlIDfp6MEhrr6JbyodJqqNQE9NYYhNAUkReItMbNE8+Qr3A4x4SNJk+VMdQScAUC84JNnnAf9IQTiCoNoOdde82R4aBebOp+VB3NvepmWkWApUATodbW/xFYPJkP/ko=,iv:aZ9lBEdVOD8f8WKHdAYsbu6VHRhs+UYKBYWE2q+ZZ38=,tag:muDHWryEuD4JtpLL0Fi+xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
