apiVersion: v1
data:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:q56TpOr18AXXRF2rzvBxryOCRcGI0TYi6tiNx0Pbsik1lZ2YZOgXQB9SUPqrwUDeuu6QQa8Bpx/wgmmfEEex2fxP5SK9CbmApLJuAG6FMWQbvot2XJEbEpaxDR0r6CcaQQWK25YWgIydkNo71SYjcaa22QIB1J8V7ZB+N6cQao15cSWjh42Zjt8vGcM26rntEkNSB614urczHkbzvsy98yIlBCmFlGYwdaF5x8YXQWhmeLkgpoVPFX6zOV04Zx28VY+/vpqiQxc0hekyo5wnrrHMRC9GW/xLyGNGFzx50pJEU4nVXwrTLTDaoZ4ZT+JaDwCPA1vEGiQ=,iv:mNgkRFXiWxv7TVU1TPdyGEkb+zZezQHA3CkMR9wILEA=,tag:b+TF2R+CWAgq/swI2ZLB/g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: admin
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nv2kd8a0ev2cny9mg507nz73jsk8n2j7708afatughslnz5pduzqgj0mq7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5MS9yczBtRzltZDlZbVYx
            VmJlbytabXBjdm43QjRNbnBLVVFza0d0TGpVCjRaNmVuZ3l2Y0tOTUFaN1dwWk5L
            YXlMWmtDbWpLbnZjM3N0cTNzSCtQdnMKLS0tIDFsbnk4dmdhd2xHWlNUOFFQOU91
            TjhseVBJRlRpY2ZNMkpON1dwMTEvSHMKYswSLBHHfM5fyk47gDzU2fWwawbwiMiR
            4X2SkaxFo51I6FUkVaYUsQS/z/0P7BOH3ufESZE2EuTxWW0XQhTEpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T14:06:45Z"
    mac: ENC[AES256_GCM,data:TJ2L3KpbZyO8c2n2QZ9Yzv/ZnetVfaL2rzZZAc4fdnKUXgsU7mNyTyX6q6XYY3f8/omkIloBBa2HssS0xU+mONfG7pxb7zwJscm2zaJgsEAizFXTndmbT8Th7wbnQXOfB227o87x9GN2CgHDlHQGEanPcb5Y6xUNczPAUneOmBk=,iv:41by4MmQ/NtA0wT/ipYtZdnrdNBwNHqQ/Lx5z2VsVXY=,tag:orygRTO7v+ZwcEouuJQvMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
