apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: admin
stringData:
    credentials.json: '{"AccountTag":"<ACCOUNT_TAG>","TunnelID":"<TUNNEL_ID>","TunnelSecret":"<TUNNEL_SECRET>"}'
