apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc
  namespace: admin
spec:
  accessModes:
    - ReadWriteOnce
  # This line is the magic link to Longhorn
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
