all:
  hosts:
    draupnir:
      ansible_host: 192.168.69.77
      ansible_user: david
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    alexandria:
      ansible_host: 192.168.69.5
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
