apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - storage.yaml
  - paths-ingress.yaml
  - local-ingress.yaml
  - jellyfin/
  - jellyswarrm/
  - lidarr/
  - prowlarr/
  - radarr/
  - romm/
  - sabnzb/
  - seer/
  - sonarr/
  - sonarr-anime/
  - tunarr/
