#cloud-config
# Generated by Terraform for cluster: ${cluster_name}
# This template prepares an Ubuntu Server VM for Kubernetes.

hostname: $${HOSTNAME}   # Proxmox sets this from the VM name at clone time
manage_etc_hosts: true

# ---------------------------------------------------------------------------
# User
# ---------------------------------------------------------------------------
users:
  - name: ${vm_user}
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
%{ for key in ssh_public_keys ~}
      - ${key}
%{ endfor ~}

# ---------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------
package_update: true
package_upgrade: false

packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - nfs-common       # Longhorn / NFS PVs
  - open-iscsi       # Longhorn iSCSI
  - qemu-guest-agent # Required for Proxmox to report VM state
  - jq

# ---------------------------------------------------------------------------
# Kernel modules – must be present before kubelet starts
# ---------------------------------------------------------------------------
bootcmd:
  - modprobe overlay
  - modprobe br_netfilter

write_files:
  - path: /etc/modules-load.d/k8s.conf
    owner: root:root
    permissions: "0644"
    content: |
      overlay
      br_netfilter

  - path: /etc/sysctl.d/99-kubernetes.conf
    owner: root:root
    permissions: "0644"
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

# ---------------------------------------------------------------------------
# Runtime commands
# ---------------------------------------------------------------------------
runcmd:
  # Apply sysctl settings
  - sysctl --system

  # Disable swap permanently (required by kubelet)
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # Enable & start qemu-guest-agent so Proxmox / Terraform can detect VM readiness
  - systemctl enable --now qemu-guest-agent

  # Ensure open-iscsi is running (needed by Longhorn)
  - systemctl enable --now iscsid

timezone: UTC

power_state:
  mode: reboot
  delay: now
  message: "Rebooting to apply kernel parameters"
