---
- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: Create njord media mount point
  file:
    path: /mnt/njord
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create alexandria mount point
  file:
    path: /mnt/alexandria
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Mount alexandria NFS share
  mount:
    path: /mnt/alexandria
    src: 192.168.69.5:/mnt/mimmis
    fstype: nfs
    opts: rw,sync,hard,intr
    state: mounted

