apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-ingress
  namespace: admin
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: syncthing.yggdrasil.rip
    external-dns.alpha.kubernetes.io/target: "14dba35c-b082-4cf5-8319-05b87f07357c.cfargotunnel.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Syncthing (draupnir)"
    gethomepage.dev/group: "Storage"
    gethomepage.dev/icon: "syncthing.png"
    gethomepage.dev/description: "File sync — draupnir node"
spec:
  rules:
  - host: syncthing.yggdrasil.rip
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: syncthing
            port:
              number: 8384
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-alex-ingress
  namespace: admin
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/hostname: syncthing-alex.yggdrasil.rip
    external-dns.alpha.kubernetes.io/target: "14dba35c-b082-4cf5-8319-05b87f07357c.cfargotunnel.com"
spec:
  rules:
  - host: syncthing-alex.yggdrasil.rip
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: syncthing-alexandria
            port:
              number: 8384
