apiVersion: v1
kind: Secret
metadata:
    name: pia-credentials
    namespace: knarr
stringData:
    username: ENC[AES256_GCM,data:5gqTirm5MmM=,iv:+4y9HSyH+eDJ3U3asZl8XjlAv8vy3IShImEjhgI5BrI=,tag:QTYnP5/Sb54TuAzSXGteWg==,type:str]
    password: ENC[AES256_GCM,data:MxKAWvU2mqvP/y3F4zGD6m1UdZUHow==,iv:sQxBX3o00rWU7KGjZHkJ56UnHuaqxrK2iqUOWaCzYZs=,tag:ISktDbN0JVLg6r3BqUv52w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x23xy95kpc6h3ql9x4q35r8r2g5yd0mjejggz55a2mnc5muwys2qreflxt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWm1lblB1NDU0UjRXN3la
            dHFpUHlkMWRnYnJicGVJYmFBdTBiL3VwU1M4CmJ3L1BBN21uVTdFa2UyVHFtYWo5
            WU1MLzNvV1BrdjJ5b0Z3WC9xQ1BrK1kKLS0tIDY5cG1lSzVodzFFdUVJcXJKSUZr
            RVE3QnZ6QXJxbjFlOVRKdWIzL0RjWkkKKf9Ao/7PFjlGUJsztGellDvqFeV94wAM
            qeBDG2utTk6Ex/EdD/Ht7WJzgSR8B/tgLijDUadV9GTXAbRhalaTxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T15:16:14Z"
    mac: ENC[AES256_GCM,data:DPuTNBl1beCCpt9OV33z8N2MuPCzYBan95xasm5y6lKxnUDlH1yBghZj2qM0kMFczyrsIzD9fNSkYjkQHjBqe9xCBRt5GKQcyeA984x6/pYwsKYFWvEB2yYOn9vacnxEHn2rjnZbmYcaU9rTy7B5eCZZy5UiuhAyTD3lneGPJYg=,iv:1fwrmTgrKKJvUvgW3YI+UMz6aw0cEiysecReZGijXjU=,tag:sr4bIV+e4t/yPlWGm26chQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
