apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-config-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.69.5
    path: /mnt/mimmis/k8s-config/actual-budget
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-pvc
  namespace: admin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: actual-budget-config-pv
  resources:
    requests:
      storage: 5Gi
