apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://192.168.69.5:/mnt/mimmis/longhorn-backups"
  credentialSecret: ""
  pollInterval: "30m0s"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-replica-count
  namespace: longhorn-system
value: "1"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-over-provisioning-percentage
  namespace: longhorn-system
value: "200"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-reserved-percentage-for-default-disk
  namespace: longhorn-system
value: "10"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-minimal-available-percentage
  namespace: longhorn-system
value: "10"
