apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-n8n
  namespace: auto
spec:
  stripPrefix:
    prefixes:
      - /n8n
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-heimdal-ingress
  namespace: auto
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auto-strip-n8n@kubernetescrd
spec:
  rules:
  - host: yggdrasil.rip
    http:
      paths:
      - path: /n8n
        pathType: Prefix
        backend:
          service:
            name: n8n-svc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: auto
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # This line triggers the robot to get a cert
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  # This section tells Kubernetes "This domain uses this secret for SSL"
  tls:
  - hosts:
    - n8n.drip.yggdrasil.rip
    secretName: n8n-tls-secret
  rules:
  - host: "n8n.drip.yggdrasil.rip"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-svc
            port:
              number: 80
