apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: auto
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    external-dns.alpha.kubernetes.io/target: "14dba35c-b082-4cf5-8319-05b87f07357c.cfargotunnel.com"
spec:
  rules:
  - host: "n8n.drip.yggdrasil.rip"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n-svc
            port:
              number: 80
