apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-config-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.69.5
    path: /mnt/mimmis/k8s-config/n8n
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: auto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: n8n-config-pv
  resources:
    requests:
      storage: 20Gi
