---
- name: reload nfs exports
  command: exportfs -ra

- name: restart nfs
  systemd:
    name: nfs-kernel-server
    state: restarted

- name: restart samba
  systemd:
    name: smbd
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart syncthing
  systemd:
    name: syncthing@david
    state: restarted
